### ISSUE TITLE
Venator Air Defence System

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#100]
Add a method of activating air defence turrets on ships to defend against incomming enemy aircraft.

Using 3AS_Venator_Cannon. Ideally the system might be a module that you can sync to objects to set it up? or two modules, one for the defence cannons and one for the control stations, or be able to define certain object classes as x and others as y.

**Comment by ThatArcanist** [comment]
Myself and my Assistant will see what we can get started on
