### ISSUE TITLE
40mm pellet shot

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#101]
**Describe the bug**
After hitting a surface, instead of bouncing they decide to stick to it and go straight down until they hit something again

**To Reproduce**
1. Go somewhere with the RD-4 or underbarrel
2.  shoot the pellet round at a surface
3. ...
4. profit?

**Expected behavior**
The pellets will just go straight down instead of bouncing

**Mods List:**
 - MokTech Industries - Core: Y
 - MokTech Industries - Armoury: Y
 - MokTech Industries - Factions: Y

**Comment by m0kka** [comment]
I think Rat has done an excellent job improving the bounce of the pellet, closing
