### ISSUE TITLE
Field Support Vests

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#110]
Add the following vests as "Field Support Suspenders" (equivelant values to P2):

**White**
- [ ] Clone trooper suspender (white) - JLTS_CloneVestSuspender_white

**Grey**
- [ ] Clone trooper suspender (41st Gree) - JLTS_CloneVestSuspender_41_Gree

**Black**
- [ ] Clone trooper suspender - JLTS_CloneVestSuspender

**Comment by Rat1452** [comment]
Done, kek W
