### ISSUE TITLE
Field Support Vehicles

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#111]
The following list of vehicles need to be added for Field Support's use:

Tanks

- [x] TX-130 - 3as_saber_m1
- [x] TX-130 Recon - 3as_saber_m1Recon
- [x] TX-130 Super Saber - 3as_saber_super*

Troop Carriers
- [x] RTT Wheeled - 3AS_RTT_Wheeled*
- [x] UT-AT - 3as_UTAT**
- [x] HAVw A6 Juggernaut - 3as_Jug**

Artillery
- [x] ATAP - 3AS_ATAP_base
- [x] AV-7 - 3as_AV7

*add option to "Deploy" vehicle, deploying a vehicle should remove the fuel or prevent the engine starting and then enable the option for any nearby Field Support member with the Backpack to use the vehicle as a **Medium Fortifications** Container

**same above except add the option to use the vehicle as a **Large Fortifications** Containter

**Comment by m0kka** [comment]
Vehicles marked with * and ** should also spawn with the Small Fortifications crate in cargo.
Vehicles marked with ** should additionally spawn with the Medium Fortifications crate in cargo.

**Comment by m0kka** [comment]
all of these are done
