### ISSUE TITLE
Ammo Weight Balancing

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#115]
Increase size of Valken magazines (MTI_Valken38X_mag to equal 0.45kg (same as 15x - MTI_DC15X_mag)

Increase size of Z-6 magazine (MTI_Z6_Small_mag) to 1.04kg, the same as the DC-15L magazine (MTI_DC15L_mag)

**Comment by Hirisu** [comment]
should be done with weight updated branch
