### ISSUE TITLE
Field Support Weapons Crates

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#116]
Add the following (wide) Supply Boxes:

**Mortar**

- [x] 2x [SOB] Mortar - MTI_Mortar_Carry
- [x] 4x Artillery Range Table - ACE_artilleryTable
- [x] 20x [SOB] Mortar HE Round - MTI_1rnd_Mortar_HE
- [x] 10x [SOB] Mortar Guided Round - MTI_1Rnd_Mortar_Guided
- [x] 10x [SOB] Mortar Illumination Round - MTI_1Rnd_Mortar_Illum
- [x] 10x [SOB] Mortar Smoke Round - MTI_1Rnd_Mortar_Smoke
- [x] 6x [SOB] Mortar Smoke Round (Red) - MTI_1Rnd_Mortar_Smoke_Red

**Heavy Repeater**

- [x] 2x [SOB] Heavy Repeater - MTI_HeavyRepeater_Carry
- [x] 20x [SOB] 1000rnd Heavy Repeater Magazine - MTI_HeavyRepeater_1000Rnd_csw_mag

**Comment by m0kka** [comment]
The actual weapons are to be deployed through fortify directy

**Comment by m0kka** [comment]
done
