### ISSUE TITLE
cTab, but Star Wars

### ISSUE THREAD

**Issue by ThatArcanist** [Special-Operations-Brigade/SOB-Issue-Tracker#117]
- A Star Wars-looking variant of the cTab
    - Placeholders for future pages (like calling Orbital Bombardments)

Mokka asked for it abit ago just making a ticket so that its known i'm working on it

**Comment by m0kka** [comment]
@ThatArcanist if possible, can you also look at including #90 in this process?
should be as simple as putting an additional line in the item's config

**Comment by ThatArcanist** [comment]
Yeah, although i'm skeptical it won't be as cut and dry, i'll assign it to myself for now

**Comment by m0kka** [comment]
this is nearing completion, the only major work item that needs to be done is modifying the ui images/icons/etc to be more star wars-like (maybe even sob branded)

**Comment by gumbekk** [comment]
catTab is incorporated this now, going to bump this
