### ISSUE TITLE
Celt Unit loadouts Update

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#119]
Please update my spawnable unit with the attached files

Phase 2 loadout - Celt MC loadout
Republic Commando Loadout - Celt RC Loadout
[Celt MC loadout.txt](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/files/9964902/Celt.MC.loadout.txt)
[Celt RC Loadout.txt](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/files/9964903/Celt.RC.Loadout.txt)

**Comment by m0kka** [comment]
closing as no longer relevant
