### ISSUE TITLE
Vehicle Control System Bugs

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#120]
Some bugs we found while testing VCS on mp:

- [ ] "Activate Console" action only appears for player that placed module
- [ ] Venator Cannons do not target air vehicles

I know the venator cannons having borked targetting is not our fault, but we'll have to fix it in order to be able to permanently use VCS in its point defense capacity

Activation itself and the responsiveness in mp works great!

**Comment by ThatArcanist** [comment]
For the first issue, is that for the Zeus module only or does it include the Eden Module?

**Comment by m0kka** [comment]
Ah, we only verified with the Zeus module just now. unknown about the 3den one

**Comment by ThatArcanist** [comment]
@m0kka Can this be closed now? I think both are done
