### ISSUE TITLE
Assassin Overhauls

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#125]
Couple of small things for assassins, as previously discussed.

- [x] Add Dera/Lath A-I mags to DC-15X (and only add those mags to CovOps arsenal)
- [x] Change NT deployment to (un)pack to/from launcher slot using keybind, directly into hand
- [x] Add EMP AoE round for NT (same as the JLTS EMP launcher uses)
- [ ] Find a way to make IMS stealth executions actually viable in the field
- [ ] Add a Stealth variant of the Prowler (with active camo)
- [ ] Add a Stealth variant of the MSE-6, with an EMP AoE self-destruct
- [x] Add Tazer to assassins

**Comment by Hirisu** [comment]
done the first one

**Comment by gumbekk** [comment]
Done 4th,
think we can just close this as we have https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/issues/209 for the IMS stealth executions and make MSE a new post

**Comment by m0kka** [comment]
agreed
