### ISSUE TITLE
TX Buffs

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#127]
- [x] Increase TX speed over land (especially off-road)
- [x] Increase fuel consumption rate
- [ ] If commander turns out, their turret cannot be turned/elevated properly anymore and it's almost useless

**Comment by Hirisu** [comment]
Fuel consumption rate can only be changed indirectly by increasing the RPM rates, instead i reduced fuel capacity for now as it achieves similar purpose. 

Regarding Speed: 
i increased max speed by 15km/h for normal and super saber / 30 for the Recon Variant
Engine power for normal and super got increased by 100 and Recon 150
Peaktorque ofr normal and super got increased by 200/ Recon got 350

**Comment by m0kka** [comment]
closing this, as the turret behaviour is outside our control sadly
