### ISSUE TITLE
Ability to escape handcuffs/capture

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#133]
Active ability/"mini-game" for players.
Random chance based on skill rating/config setting for AI.

**Comment by m0kka** [comment]
just collecting some ideas for the mini-game/skill-check:

- Dead by Daylight skill check
- Button mashing mini-game

**Comment by Hirisu** [comment]
Connect dots, where lines can not cross over each other?

A Field of tiles with lines directed towards other tiles, with a starting point and endpoint, where the line needs to go to the other.

**Comment by ThatArcanist** [comment]
Would require some UI, would be good practice as well as a mental reset from the tech project

**Comment by ThatArcanist** [comment]
Assigned @Rat1452 as well, I'll use this to teach him how to make UI

**Comment by m0kka** [comment]
Legends, thank you
UI aside, this should be pretty straight-forward

**Comment by ThatArcanist** [comment]
I think we're gonna go with a button mash skill check, this lines up with most games that have some kind of "escape" feature

**Comment by m0kka** [comment]
Yeah, solid, I agree

**Comment by gumbekk** [comment]
I know I'm not Mokka but it seems we always carry knives and we're only dealing with zip-ties

**Comment by m0kka** [comment]
I agree with Chimera: every clone has *something* on their person to facilitate a rather easy escape from simple restraints.
My solution to this would be adding a second "tier" of restraints - that would additionally be limited to CQC roles

**Comment by ThatArcanist** [comment]
Mokka finished this 🙏🏻
