### ISSUE TITLE
Ark, Zyys and Stuka backpack missing logo

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#137]
**Describe the bug**
Zyys, Ark and Stuka backpack is missing the squad logo

**To Reproduce**
1. Go to Ace Arsenal
2. choose one of the three corresponding backpacks (6,9,13)
3. See error

**Mods List:**
 - MokTech Industries - Core: Y/N
 - MokTech Industries - Armoury: Y/N
 - MokTech Industries - Factions: Y/N

**Comment by m0kka** [comment]
Handed off to Texture Team, @Hirisu you'll have to re-submit your designs with a "legal" version of the logo attached

**Comment by Hirisu** [comment]
outdated with upcomming texture changes
