### ISSUE TITLE
Emergeny Beacon Additions

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#142]
Add Emergency Beacon functionality to ARC, Assassin and Pilot equipment.

**Comment by m0kka** [comment]
Remaining Task List for Assassins:

- [ ] Create new assassin-specific backpacks based on existing P2 backpacks (Epsilon's choice)
- [ ] Make sure to copy-paste BACKPACK_MAXLOAD define from Phase2 script_component.hpp
- [ ] Add Beacon to new backpacks
- [ ] Add Squad Shield to new backpacks
- [ ] Add new backpacks to config_lists
- [ ] Add new backpacks to covert-ops whitelist

In core:
- [] Remove Squad Shield grenade from covert-ops arsenal whitelist

**Comment by Hirisu** [comment]
above all done
