### ISSUE TITLE
Self-interaction for demo peeps to place red/blue flag on current pos

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#151]
To document clear/dangerous areas

**Comment by ThatArcanist** [comment]
Associated to an item like Spray paint?

**Comment by m0kka** [comment]
Yeah, that might be a good idea, like a "blue flag" and "red flag" item with minimal weight

**Comment by oliv3lrg** [comment]
can we not just have it be _in_ the backpack to avoid having to have them in the inventory of people, backpacks are bursting at the seams as it is

**Comment by ThatArcanist** [comment]
The flags could see purpose outside of EOD. We can make the item virtually weightless

**Comment by m0kka** [comment]
done, marker flags can either be deployed from an inventory item, or unlimited by player with demo perms
