### ISSUE TITLE
MokTech Blaster Enhancement

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#157]
~~Change all our blaster bolts, with the exception of the Bowcaster, to use Orange Bolts, signifying their pass through the MokTech Industries Workshop!~~

**Comment by Hirisu** [comment]
just to be clear, does that include republic weaponry (DC 15-A/S/S, 17m etc.)

**Comment by m0kka** [comment]
Especially those, yes

**Comment by m0kka** [comment]
Updating this due to the quite vocal feedback we've received about this suggestion.
Changing Mokka's pistol to orange bolts, Celt's pistol to yellow bolts, everything else stays as-is.

**Comment by Hirisu** [comment]
yellow won't be a problem as that already exists, orange needs to be made

**Comment by m0kka** [comment]
![image](https://user-images.githubusercontent.com/10928841/215295144-fa06f402-bfd4-4617-a8af-04c95652c133.png)

**Comment by m0kka** [comment]
although they won't have the cool lighting effect, so I guess we *do* have to make it properly after all :c

**Comment by Hirisu** [comment]
ye saw that one, we could have it as a temporary option

**Comment by m0kka** [comment]
nah, we'll do it properly straight away
stopgaps always make the best permanent solutions
