### ISSUE TITLE
little sentry turret that you can deploy from inventory

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#160]
already prepping for technician/droidwrangler

**Comment by ThatArcanist** [comment]
thats hot

**Comment by m0kka** [comment]
RC technician will get a few drones to choose from, as the second pillar of their MOS

1. tech tablet / hacking
2. utility drones galore

**Comment by m0kka** [comment]
maybe ARC tech, too, no idea, we'll see

**Comment by ThatArcanist** [comment]
Finished :)
