### ISSUE TITLE
Find a way to allow Pilots to quickly airdrop multiple containers at once

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#161]

**Comment by m0kka** [comment]
Addendum to this: the supplies that get dropped via parachute should spawn with an Orange Smoke/Light attached to be easier to find for friendly troops

**Comment by Rat1452** [comment]
I think I know a way for this, which aircraft should have it? LAAT and nu-class?

**Comment by oliv3lrg** [comment]
All our LAATs (including LE) and the Nu-class, yeah

**Comment by ThatArcanist** [comment]
@m0kka With the recent supply crate changes, I don't believe this is needed. We actually had someone air drop supplies to us a week or two ago. Crates already deploy a chute and pop smoke once they touch the ground.

**Comment by m0kka** [comment]
agreed, would be cool to change the smoke colour to orange in accordance with sop, but that would be a new ticket altogether. closing
