### ISSUE TITLE
Switch left shoulder weapons to BC Two Primary Weapons

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#164]
https://steamcommunity.com/sharedfiles/filedetails/?id=2703656123
https://github.com/RobinDX/BC-Two-Primary-Weapons

will require some additional legwork to set up properly, but will be worth it in the end

**Comment by Hirisu** [comment]
made all the no brain work since i was bored, don't know the next step

**Comment by m0kka** [comment]
done, thanks ark
