### ISSUE TITLE
Verp improvements

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#166]
**(As dragged out of Cats suggestion etc)**

Bullet drop is excessive OR needs to be faster + stronger
 
Overheat could be a bit shorter

Red dot adjustment doesnt help

Range needs work, doesnt work as CQC rifle or DMR right now (linked to bullet drop/speed)

**Comment by oliv3lrg** [comment]
The Scope adjustment works and ranges targets up to ~1.5km

Maybe remove the option for the holoscopes

**Comment by m0kka** [comment]
We're gonna cut the shot delay down to just about a second, gonna adjust the sound and then action it

**Comment by m0kka** [comment]
done
