### ISSUE TITLE
SOB Switch Backpack Bind issue

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#167]
Using the SOB switch backpack in the SOB section of the addon (backpack on chest) causes you to spawn 2 backpacks with only partial amounts of the original contents (Split between the two)

Taking off the backpack and putting the other one on does not fix the issue and will spawn another at the front carry position. 

The backpack will continue to pester you randomly post respawn until you abort the mission and rejoin. (Credit: Spooks)

**Comment by m0kka** [comment]
will try to reproduce

**Comment by An00biz19** [comment]
@m0kka I had no issues with the actual swap mechanic this op other than it killed my jumppacks recharging mechanic, the actual swap back and forth and contents didnt change for me

**Comment by m0kka** [comment]
should be resolved by having integrated BOC directly into core
