### ISSUE TITLE
15sc Recoil

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#170]
Recoil on 15sc is very large, and means it struggles to function as a carbine when firing full auto, DMR/stealth round is fine

**Comment by m0kka** [comment]
@Hirisu if you feel comfortable, would you take a look at reducing the recoil. maybe use the dc-17m as a reference (or another weapon with lower recon that you can think of).

**Comment by m0kka** [comment]
update: please use the jlts dc-15s recoil pattern/values for the 19SC

**Comment by Hirisu** [comment]
will do

**Comment by Hirisu** [comment]
> update: please use the jlts dc-15s recoil pattern/values for the 19SC
This is actually the current case

**Comment by Hirisu** [comment]
Pull Request is in times now
