### ISSUE TITLE
EE-2 Magazine

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#174]
EE-2 Magazine model should be hidden/invisible.

**Comment by m0kka** [comment]
be more precise

**Comment by oliv3lrg** [comment]
so you can't see it visually

**Comment by m0kka** [comment]
hidden where

**Comment by m0kka** [comment]
closed as not possible, model of the base rifle does not have a magazine proxy that would allow this
