### ISSUE TITLE
Boarding LAATs

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#177]
Two new LAAT variants with the express purpose of them being used to aggressively board capital ship hangars (and other reinforced positions).

- [ ] LAAT/br 
    - LAAT/i based
    - UAV controlled
    - Slightly up-armoured hull
    - Only ball turrets, nose guns and skyfire rockets
    - Pilot action to deploy shield and eject passengers on landing
        - Aircraft gets permanently grounded when shield has been deployed
    - Shield duration configurable, default 90s
    - Maybe a custom skin?!
    - No active sensors (only passive)
- [ ] LAAT/le (Boarding)
    - UAV controlled
    - Only guns
    - Pilot action to deploy shield and eject passengers on landing
         - Aircraft gets permanently grounded when shield has been deployed
    - Shield duration configurable, default 90s
    - Maybe a custom skin?!
    - No active sensors (only passive)

**Comment by gumbekk** [comment]
Maybe remove sensors too because those don't cheap D:

**Comment by m0kka** [comment]
ohh, good point
