### ISSUE TITLE
No Latheniol in ARC arsenal

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#178]
Command Arsenal
![image](https://user-images.githubusercontent.com/76742077/221719946-62d49256-f7e9-4635-b0b3-374278f42af2.png)
ARC Arsenal
![image](https://user-images.githubusercontent.com/76742077/221720034-7cef9310-5ed1-4979-8f72-1c2be5ae06ae.png)
Field Surgeon should have it
![image](https://user-images.githubusercontent.com/76742077/221720185-1949e53c-27c6-46a1-9a0e-c669032cd98b.png)

**Comment by Hirisu** [comment]
done
