### ISSUE TITLE
SOB Troopers still wear old equipment and are missing helmets due to texture update

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#181]

**Comment by ThatArcanist** [comment]
what

**Comment by Hirisu** [comment]
![20230305040345_1](https://user-images.githubusercontent.com/110851104/222939461-cf1c55d4-47ae-442d-9577-8669362428d5.jpg)
the units

**Comment by ThatArcanist** [comment]
OH the units okay

**Comment by Hirisu** [comment]
sorry should have clarified, if no one else wants to touch it before, i will include it in my Faction Update

**Comment by Amateur-God** [comment]
if no one has touched this by the time ive replaced my P Drive ill get on with doing it

**Comment by ThatArcanist** [comment]
@Hirisu @Amateur-God Did anyone end up looking at this (It was like a year ago so alot has changed and could've been fixed since)

**Comment by Hirisu** [comment]
Yeah, became obsolete with the switch to p1
