### ISSUE TITLE
Modification to Verpine Scope

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#183]
Modify the Verpine Scope slightly. It's hard to aim at a target the completely hidden by the bottom black arrow. Happens at >1700m.
![image](https://user-images.githubusercontent.com/76742077/224822348-09d45a8e-64cd-4d73-badd-9fae849e5749.png)
(Person is at 2000m, scope is zerod for 1700m)

**Comment by oliv3lrg** [comment]
this is by design, it's a marksman rifle, not a sniper rifle it shouldn't be hitting things at 2km
