### ISSUE TITLE
ARC Backpack on Chest

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#184]
Nothing major but with the wrist rocket on the backpack model it looks a bit weird
![image](https://user-images.githubusercontent.com/76742077/226446124-7b27b4f8-8a12-441b-8e20-e21553faa90e.png)

**Comment by m0kka** [comment]
ahhhh, yeah, fair
not entirely sure how to go about fixing this, hmmm

**Comment by m0kka** [comment]
realistically, the best way to fix/prevent this is by rewriting the backpack-on-chest script with some very slight alterations, which should allow hiding the gauntlet when the backpack gets swapped

**Comment by Amateur-God** [comment]
is the gauntlet a hidden selection? if so couldnt you do an if is typeof with the parent class of all the ARC backpacks to hide the hidden selection when moving to chest?

**Comment by m0kka** [comment]
aii that is the plan, it just requires rewriting or at least integrating the backpack on chest functionality into core, since Zade's BOC does not provide any bindings/events to facilitate this (AFAIK)

**Comment by m0kka** [comment]
a BOC overhaul is due anyways, to fix the TFAR issues, LR getting reset etc
