### ISSUE TITLE
Armbands

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#186]
Add all the phoenix armoury armbands to all arsenals except for the RC arsenal (they don't fit)

**Comment by gumbekk** [comment]
this can be closed?

**Comment by Hirisu** [comment]
nah not done yet, i will do it after the meeting

**Comment by m0kka** [comment]
this will need to be done again (if it was already completed) since the class names for the arm bands changed with the last Phoenix Armoury/Core update

**Comment by gumbekk** [comment]
Is there an announcement/changelog channel in Phoenix and JLTS Extended we can follow for other-mod-news channel?

**Comment by m0kka** [comment]
done
