### ISSUE TITLE
Scythe Turret

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#189]
Error code:

No entry 'bin\config.bin/CfgVehicles/mti_factions_cis_Scythe/Turrets/MainTurret.soundElevation'

Many thanks to Rat

**Comment by Rat1452** [comment]
Me: Has an active bug thread going and already working on it 
You: Opens an issue for it

**Comment by m0kka** [comment]
Don't talk back to our secretaries, they're doing their best Ò.ó

**Comment by ThatArcanist** [comment]
@m0kka @Rat1452 What's the status on this?

**Comment by Rat1452** [comment]
Fixed
