### ISSUE TITLE
NT Adjustments.

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#193]
Increase overall weight of NT Rounds, as it does massive damage. Forces NT user to have less other ammo/supplies, or reliance on their teammates.

Additionally, usage of the NT EMP rounds would give more things to do with the NT outside of boom.

**Comment by m0kka** [comment]
this will be actioned as per the ticket, you're the cov-ops boss after all

@Hirisu would you look at increasing the nt mag weight, by a factor of 1.5 maybe?

**Comment by Hirisu** [comment]
will do
