### ISSUE TITLE
LAAT/LAG: only allow pilot to activate shield

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#198]
this is no longer optional, make it so @ThatArcanist @Rat1452

**Comment by ThatArcanist** [comment]
![image](https://user-images.githubusercontent.com/8608529/236645408-41971d43-683b-40ad-abfe-b361821d1566.png)

**Comment by ThatArcanist** [comment]
In PR

**Comment by m0kka** [comment]
this was merged and resolved
