### ISSUE TITLE
Shadow Trooper Armour

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#200]
Add the following to the Shadow Trooper Armour:

- Intercom
- Emergency Beacon
- Rebreather

**Comment by Amateur-God** [comment]
started working on it with [Shadow Trooper Armour](https://github.com/Special-Operations-Brigade/MokTech-Armoury/tree/Shadow-Trooper-Armour-%23200)

**Comment by Amateur-God** [comment]
Intercom added, need to work on Rebreather and Beacon however as far as im aware, rebreathers can only be added to vests and Beacons can only be added to backpacks of which ShadowTroopers have neither @oliv3lrg how would you like me to proceed if those are required for the last 2 features?

**Comment by oliv3lrg** [comment]
We'll add some Shadow Trooper Backpacks and vests with increased capacity equal to the Assassins and some other backpack textures

**Comment by Amateur-God** [comment]
From Celt in discord

Shadow Trooper Vests

Platoon Command Vest - mti_armoury_trooper_vest_PlatoonCommand > To be Named Shadow Trooper Sergeant Vest
Lance Corporal Vest - mti_armoury_trooper_vest_CLC > To be Named Shadow Trooper CLC Vest
Specialist - mti_armoury_trooper_vest_CSP > To be Named Shadow Trooper Specialist Vest
Holster - mti_armoury_trooper_vest_base > To be Named Shadow Trooper Holster

Shadow Trooper Backpacks

Mini LR > Shadow Trooper Mini LR
RTO Pack > Shadow Trooper RTO Pack
Clone Trooper Backpack > Shadow Trooper Backpack
Belt Bag > Shadow Trooper Belt Bag

**Comment by Amateur-God** [comment]
Just waiting on textures to complete

**Comment by oliv3lrg** [comment]
can we just push these with normal textures for now please

**Comment by oliv3lrg** [comment]
also need to add the rest of the rank vests

**Comment by Amateur-God** [comment]
So add rank vests and push?

**Comment by oliv3lrg** [comment]
yes, make sure they have equivalent stats to the assassin ones

**Comment by Amateur-God** [comment]
anyone able to assist, I'm not sure how soon ill be able to get the rest of this done

**Comment by Amateur-God** [comment]
these should now be added in https://github.com/Special-Operations-Brigade/MokTech-Armoury/tree/Shadow-Trooper-Armour-%23200

**Comment by Amateur-God** [comment]
link updated to the latest post HEMTT branch
