### ISSUE TITLE
Field Support Arsenal

### ISSUE THREAD

**Issue by TitaniumSatan** [Special-Operations-Brigade/SOB-Issue-Tracker#205]
**Describe the bug**
The field support arsenal does not have all the items they are supposed to. They do not have any NVG or explosives that are required to have in the kit guide for SOB.

Explosives:
Anti-Personnel Tripwire Mine
APERS Mine Dispenser
HX-AT Mine
M18A1 Claymore
VS-50 Anti-Personnel Mine

NVG's:
Clone Trooper Macrobinocs White/Grey
Clone Trooper Rangefinder White/Grey
Clone Trooper Macrobinocs NCO
Clone Trooper Rangefinder NCO
Phase 2 NVG Chip
Clone Commander Visor

**To Reproduce**
1. Go into the Field Support Arsenal
2. See that the items are not there

**Expected behavior**
For the items to be there?

**Mods List:**
 - MokTech Industries - Armoury: Y

**Additional context**
Love you Mokka

Edit: Added the names of NVG's and Explosives as per kit guide.

**Comment by m0kka** [comment]
done c:

**Comment by gumbekk** [comment]
I don't see any NVGs inside the FS arsenal post update
![image](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/76742077/69d496ad-2138-4cbd-8d98-08f1791d29ad)

**Comment by m0kka** [comment]
because those are in Armoury, and Armoury has not yet been updated c':
