### ISSUE TITLE
Create additional Supply Boxes that contain mixed supplies for platoons

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#208]
Idea is still in its infancy and entirely open for discussion, but I want to think about creating some additional prefab supply boxes which contain more mixed supplies.
These boxes would be the primary choice for quickly resupplying a platoon, without the need to request and transport the complex cluster of boxes we currently require.

New crates:

- [ ] "russian doll" large crates which have smaller supply crates in their ace cargo (eg.: ARC Supplies, RC Supplies, Platoon Supplies)
- [ ] Vehicle ammo crate

**Comment by Rat1452** [comment]
A lot of teh ARC and RC supplies are intertwined, we could rework it so its more like primary crate, secondary, launcher, specialized, etc etc

**Comment by m0kka** [comment]
will be addressed by #299
