### ISSUE TITLE
A multi-purpose "truck" for Field Support

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#210]
I'd like to make a Star Wars equivalent of the HEMTT truck from base Arma: A vehicle that can fill a variety of logistical needs, from troop transport, over hauling cargo to serving as an ambulance/mobile supply depot.

Below is a possible visual of said truck, that Pariah has sent me before:

![](https://media.discordapp.net/attachments/1025746336068415508/1108830871378735145/Screen_Shot_2020-01-27_at_9.05.05_PM_1024x1024.png)

**Comment by m0kka** [comment]
To add onto this: I would like to implement a cargo/box system for this truck that is very similar to the box loading/unloading available for the 3CB MAN trucks.
Truck should also have at least three seats in any configuration.
Want to consider an armed variant of the truck, with a turret on a swivel that can be used for point defense and to dispatch smaller amounts of infantry

**Comment by oliv3lrg** [comment]
If you didn't want to model or purchase one, you could use the ITT from 3AS

**Comment by m0kka** [comment]
yeah, but does the ITT have a cargo bed?

**Comment by oliv3lrg** [comment]
ahh I missed the 3CB Comment
