### ISSUE TITLE
FOB Crate addition

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#212]
Add a limited, 1 per box, Bacta tank to the FOB Parts Fortify Container.

lsb_BactaTank_Turret

**Comment by m0kka** [comment]
does it work now?

**Comment by m0kka** [comment]
or is just for decoration?

**Comment by oliv3lrg** [comment]
it works, can get in and heal yourself or put someone inside and heal them, both with a scrollwheel action

**Comment by m0kka** [comment]
nice, so it'll go with other functional objects

**Comment by m0kka** [comment]
done
