### ISSUE TITLE
Duplicated Perms Selection / Make Perms Selection less crowded

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#213]
![image](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/76742077/5c03ad17-ef2f-4d66-93ee-090bbbd7f8ce)
Tech shows up twice if you don't want to read the Comic Sans

**Comment by m0kka** [comment]
thanks for the report, my mistake
part of this ticket will be making the perms selector less crowded
