### ISSUE TITLE
EE-2 Adjustments

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#218]
The EE-2 rifle needs to be largely modified, the rifle should have similar capabilities to the Valken in addition to having a 3 round burst. Currently the round is slow moving and underpowered.

**Comment by ThatArcanist** [comment]
@Hirisu @Rat1452 Can either of your gents address this? would be pog if we could have it done before the update this week

**Comment by Rat1452** [comment]
I won't have time to do so before update this week, will have to be someone else

**Comment by Hirisu** [comment]
will do

**Comment by Hirisu** [comment]
done
