### ISSUE TITLE
Non Commando System Refills

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#222]
As far as I know it's not possible to refill certain systems from the arsenal like commandos can. Don't think anyone has needed it to this point (why it's marked as low priority) but I don't see it shouldn't be added. Systems are as noted (I might've missed/ some)
Everyone: Emergency Beacon
ARC: Reload MM9 and ST91
Covert-Ops: ST91 and Squad Shields

**Comment by Hirisu** [comment]
MM9s and ST91 are reloaded manually through inventory items

**Comment by gumbekk** [comment]
There's still no way to recharge the beacon on all of them still, also the commando refill still goes through the ST91 reload so I brought those up
