### ISSUE TITLE
AT-TE point defense weaponry broken

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#234]
**Describe the bug**
AT-TE PD weaponry broken. The 250 round mag reduces itself to 2 shots.

**To Reproduce**
1. Spawn AT-TE
2. get in the commander seat
3. you may have to switch seats or re enter a few times

**Mods List:**
 - MokTech Industries - Core: Y
 - MokTech Industries - Armoury: Y
 - MokTech Industries - Factions: Y

**Comment by Rat1452** [comment]
I think this is a 3AS issue because we use their weapons, I'll make a mti version at some point

**Comment by m0kka** [comment]
closing this as (sadly) no longer relevant
