### ISSUE TITLE
ZEN Context Action to remotely open unit's medical menu

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#237]
In my head, this seems relatively simple and straight-forward, who knows

**Comment by gumbekk** [comment]
Added to ACE as of update 3.16.2

**Comment by gumbekk** [comment]
I guess it's not a zen context menu now that I think about it so I'll reopen it

**Comment by gumbekk** [comment]
Should I reorganize reset medical state and reopen medical menu into it's own "drop down"

**Comment by ThatArcanist** [comment]
Can you post a screenshot of what you're talking about?

**Comment by gumbekk** [comment]
![image](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/76742077/a99ce6ce-9db3-4c6a-bab1-992dfa9665b0)

**Comment by ThatArcanist** [comment]
Yes, group Medical State and Medical Menu to their own dropdown, but leave heal out of it

**Comment by gumbekk** [comment]
closed with https://github.com/Special-Operations-Brigade/MokTech-Core/pull/213
