### ISSUE TITLE
CPAS issues

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#238]
- [x] AGM CPAS doesn't properly lock onto target and just flies straight (@Rat1452 can you maybe work your magic on the CPAS AGM to be safe?)
- [x] ARC-170 mempoints got changed so the pylon attachments points are borked (a Mokka issue)
- [ ] Make more aircraft support CPAS (at least the Z-95) (also Mokka)

**Comment by Rat1452** [comment]
AGM CPAS can now lock on both IR and Laser
