### ISSUE TITLE
Integrate/Rewrite Zade's BOC into Core

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#252]
As title, add the backpack on chest functionality as a system within Core instead of relying on Zade's BOC mod.

Will work towards fixing #184 and will fix TFAR LRs getting reset when switching backpacks

See https://github.com/DerZade/BackpackOnChest/tree/master

For TFAR fix see https://github.com/dedmen/BackpackOnChest/commit/d56b8b2d83a9db92289e75fc1e9c740c7185e2c1

**Comment by gumbekk** [comment]
Did the jetpacks stop charging when they got swapped too?

**Comment by m0kka** [comment]
> Did the jetpacks stop charging when they got swapped too?

no clue, I don't have any data on it
will have to be a new ticket if such an issue actually exists
