### ISSUE TITLE
Maybe create a "login failed/invalid" screen for tech pad if player is missing perms

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#254]
.... Instead of just not opening the datapad at all, which is the current behaviour. Might lead people to think it's bugged instead of them missing the trait.

**Comment by ThatArcanist** [comment]
Did you add the requirement for tech permissions? I didn't add that in when I created it

**Comment by m0kka** [comment]
shelved for when it would actually be relevant again
