### ISSUE TITLE
Supply RTT Overhauls

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#260]
Turn it into a UGV so FS does not have to commit one person to sit in the thing and drive it up behind the main force

**Comment by oliv3lrg** [comment]
might run into similar viewpoint issues as the LAG, my potential fix for both is to use a holo P2 LS trooper, could work? I'm not sure how UAV stuff gets set up.

**Comment by m0kka** [comment]
closing this as irrelevant, with the mutt in our hands
