### ISSUE TITLE
Create a knockdown/ragdoll stun feature for RCs

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#262]
For visual reference see https://youtu.be/JMbBjKnUoC4?si=krcEz8JhDwJDUyKd&t=221

**Comment by gumbekk** [comment]
I would like to give this a shot if you could find what method we could use to knock people down

**Comment by m0kka** [comment]
`[_target,_shooter,_ammo] call ls_common_fnc_forceRagdoll;`

**Comment by gumbekk** [comment]
Any numbers for distance/angles? Wiki for BF2 says the AoE is 10m, and I'm guessing the angle is ~90 degrees

**Comment by m0kka** [comment]
aii let's start with those values

**Comment by gumbekk** [comment]
How is this going to be balanced? Will it be a cooldown or will it required an item for activation such as the taser. Or perhaps 1 time use. Anything to make it not have to appear on the status panel.

**Comment by gumbekk** [comment]
Unless you want to do more UI stuff

**Comment by m0kka** [comment]
> Unless you want to do more UI stuff

more concerned about if there's enough space on the ui, is all lol

let's make it a recharge-by-item, like the taser

**Comment by gumbekk** [comment]
Added with CBA settings/bindings and requires ammo
good job me

**Comment by oliv3lrg** [comment]
I would prefer B2s be unaffected

**Comment by ThatArcanist** [comment]
@oliv3lrg I think a B2 should be affected, but only slightly. instead of falling over, it should do its little like, "hit" animation so it looks like it was slightly knocked back but was able to withstand the force

**Comment by ThatArcanist** [comment]
I think that would look really cool

**Comment by oliv3lrg** [comment]
> @oliv3lrg I think a B2 should be affected, but only slightly. instead of falling over, it should do its little like, "hit" animation so it looks like it was slightly knocked back but was able to withstand the force

yeah that would be cool, I just don't want them getting knocked over

**Comment by gumbekk** [comment]
If you can find whatever Webknight function/script that makes it recoil similar to when it's damaged should just be an if statement

**Comment by gumbekk** [comment]
@m0kka Can you finish this? I did some stuff but I can't access the internet on my desktop for now, I added the attribute (albeit poorly), but couldn't get it to show up in eden, and hadn't put it on the B2 yet

**Comment by gumbekk** [comment]
I think mokka added resistances as of last update 🤞
