### ISSUE TITLE
catTab squad member dots

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#265]
What used to be Squad Member dots with numbers now don't show up with dots anymore
![image](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/76742077/0486e2f3-937c-43e6-b75b-13c538357111)

**Comment by m0kka** [comment]
good catch, I'll have to have a look

**Comment by ThatArcanist** [comment]
@m0kka Was this also fixed in the feb update?

**Comment by ThatArcanist** [comment]
@m0kka bump

**Comment by m0kka** [comment]
Should be fixed a couple updates ago, yuh
