### ISSUE TITLE
[SOB] DetPack unable to use M57(and Timer) as Trigger

### ISSUE THREAD

**Issue by magssibbert** [Special-Operations-Brigade/SOB-Issue-Tracker#282]
**Describe the bug**
The M57 Firing Device(ACE_Clacker) is unable to be selected as a Trigger for the [SOB] DetPack (MTI_DetPack), additionally the Timer Option is also not avaible. 
This in results in the DetPacks not being usable for Trooper Demo (and Rfn Arc), as according to the Kit guide they only get the M57.

**To Reproduce**
1. Go into Ace Arsenal
2. Equip a Backpack with boht the M57, and some [SOB] DetPacks.
3. Place a Detpack via ACE Explo Menu
4. Try to select a trigger and see the Option not showing up.
5. To confirm there no other issue take a [SOB] Advanced Firing Device from Arsenal and see that working

**Expected behavior**
The M57 Firing Device should be selectable as a Trigger for the [SOB] DetPack, additionally the option for Timer should probably also be avaible.

**Screenshots**
![20231124155411_1](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/45903063/4e37f85a-0246-46e9-ab0d-343210fcc44b)

**Mods List:**
 - MokTech Industries - Core: Y
 - MokTech Industries - Armoury: Y
 - MokTech Industries - Factions: Y
(Tested with most recent SOB Modlist)

**Additional context**
The same issue exists for the [SOB] EC-01 but might intentional as its intended for Commando and they have the [SOB] Adv Firiing Device. (The missing timer might still be a Bug).

**Comment by m0kka** [comment]
thanks for the report, fixed
