### ISSUE TITLE
Shadow Trooper Backpacks

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#286]
Shadow Trooper backpack capacity is incorrect, they should be equal to Assassin Backpacks

**Comment by Amateur-God** [comment]
I'll fix the intercom from #287 when I fix this too

**Comment by Amateur-God** [comment]
my bad, i forgot to add the intercom and update the backpack supply when i manually made my old version HEMTT friendly

**Comment by Amateur-God** [comment]
[Shadow Trooper Fix](https://github.com/Special-Operations-Brigade/MokTech-Armoury/tree/Shadow-trooper-fix)
