### ISSUE TITLE
CovOps Bugs Part 3 - The Disguise Kit

### ISSUE THREAD

**Issue by An00biz19** [Special-Operations-Brigade/SOB-Issue-Tracker#290]
Coming out of Disguise Kit doesn't flip individuals back to BLUFOR from Civilian. Spawned B1 and it did not shoot.

Disguise Kit prevents the use of Shadow Tech Pad, even after taking off disguise kit - probably linked to above.

**Comment by ThatArcanist** [comment]
Fixed, pending PR
