### ISSUE TITLE
Alpha Rangefinder uses wrong base model

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#295]
The Alpha Rangefinder should use the JLTS EA rangefinder to fit on the P1 helmet: SEA_P1_Rangefinder I have added multiple new texture files to the drive for Lieutenant, Sergeant and NCO versions in addition to a white version

**Comment by oliv3lrg** [comment]
Custom unit armour and equipment > ARC > Alpha Rangefinders

**Comment by ThatArcanist** [comment]
@oliv3lrg I think this is was done, can you confirm?

**Comment by oliv3lrg** [comment]
completed
