### ISSUE TITLE
Supplies Rework

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#299]
It is time to properly rework the entire supplies setup. We need less fractured/specialized crates.

Proposed Crates after rework:

- Basic Equipment
    - Contains all the basic equipment, used by all billets/roles
 - Advanced Equipment
    - Contains specialized equipment used by ARCs/RCs
 - Basic Medical
     - Enough basic medical for a Platoon
 - Advanced Medical
     - Enough medical for a Platoon incl. adv. meds used by ARCs/RCs
 - Platoon Explosives
     - Explosives & Mines incl. various clackers, for Troopers, ARCs and RCs
 - Platoon Ammo
     - Ammo for Troopers, ARCs and RCs
 - Platoon Launchers
     - Launcher Ammo and Disposables for Troopers, ARCs and RCs
 - Covert-Ops
     - Ammo, Explosives, Launcher (Ammo), Equipment used by CovOps
 - Field Support
     - Ammo, Explosives, Equipment used by Field Support
 - Pilot Emergency Supplies
     - BuildYourOwnAircraft kit, incl. super glue
 - Drones
     - Various drones + batteries
 - Mortars
     - Mortars deployed through Fortify + Ammo
 - Heavy Repeaters
     - Heavy Repeaters deployed through Fortify + Ammo
 - Vehicle
     - Vehicle Repair, Ammo & Fuel

**Comment by Rat1452** [comment]
I like the proposed one, my one concern is the adv medical and basic medical, can get tedious to grab both but I understand the separation none the less

**Comment by m0kka** [comment]
> I like the proposed one, my one concern is the adv medical and basic medical, can get tedious to grab both but I understand the separation none the less

Why do you understand the need to separate them?

**Comment by Rat1452** [comment]
Separation of who needs them, adv medical won't be used by p2s by my understanding so they would just need the basic, while arcs and RC would need both, inherently we could just combine them and just trust that everyone would grab their gear guide appropriate stuff

**Comment by ThatArcanist** [comment]
Work for redoing the resupplies began awhile ago before moving to the back burner in branch `feature/resupplies`. The currently proposed solution is as follows:

+ New "Generic" Item crate (GPS, Radio, Etc)
+ Arc Trooper Crate (Include two disposables)
+ Trooper Crate
+ Commando Crate
+ Shadow Trooper Crate
+ Assassin Crate
+ Field Support Crate (Demo, Medical, don't forget defib ammo)
+ Squad crates will now have a little less than enough to fully resupply a squad (About 3/4s of what a squad would need). Squads that are fully out of equipment should RTB for a full resupply
+ "Platoon" crates which are much larger but also contain a number of each crate for when supplies are needed en masse

**Comment by ThatArcanist** [comment]
Finished
