### ISSUE TITLE
CBA Versioning: Handler to disconnect clients with outdated MTI mods

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#303]
Add a version mismatch handler to `main`'s CBA Versioning setup to automatically disconnect clients with an outdated version of the mod. Disregard server being out-of-date (because that would make for a bad time all around).

Additionally, add a CBA Setting that enables/disables the automatic disconnect, defaulting to **disabled**. This will allow other units to make their own decision in this matter, without enforcing this method.

**Comment by m0kka** [comment]
fuck the cba setting, setting init runs after versioning checks

**Comment by gumbekk** [comment]
I believe this can be closed, but will leave it up to you

**Comment by ThatArcanist** [comment]
This is infact, finished as I got got at the last set of operations
