### ISSUE TITLE
Fix HAAD bacta selection

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#315]
couldn't be fucked doing this before release, just so I don't forget to solve this *eventually*.

**Comment by gumbekk** [comment]
I can take a look through, but I wouldn't know what it is right now, worked when I did my local builds

**Comment by gumbekk** [comment]
It seems to work without the model.cfg I guess, what happens if we just keep it out

**Comment by m0kka** [comment]
the HAAD would not be retexturable. But that's not the point, we're doing it properly, not half-ass it by removing the model,cfg

**Comment by gumbekk** [comment]
okay, I wasn't sure what the repercussions were if we kept it out

**Comment by gumbekk** [comment]
Fixed, PR has been made
