### ISSUE TITLE
Add pre-loaded Resupply variants of the MUTT

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#317]
### MUTT-I (Plt Supplies)
Should contain:
- 2x ARC Squad Box
- 2x Commando Squad Box
- 3x Trooper Squad Box
- 1x Advanced Medical Box

### MUTT-C (Cmpy Supplies)
Should contain: 
- 2x Covert Ops Squad Box
- 5x ARC Squad Box
- 5x Commando Squad Box
- 8x Trooper Squad Box
- 4x Advanced Medical Box

in addition to the "default" supplies (fuel/FS squad)

**Comment by gumbekk** [comment]
PR made, needs to be merged

**Comment by gumbekk** [comment]
merged
