### ISSUE TITLE
Rework disguises into their own addon

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#318]
Having the disguises sorta awkwardly duct-taped into equipment isn't ideal, would like to move disguises to their own addon entirely for better overview and management.

Additional work items:

- [x] fnc_equipDisguise: move `doIfSpotted` and `removeEvents` into separate functions instead of putting them in global vars (...each time the function is called)
- [x] fnc_equipDisguise: fix error with `removeEventHandler` and `CBA_fnc_removeEventHandler`
- [x] Make the ACE_Interaction menu for equipping disguises dynamic instead of having to define a new interaction entry for each new type of disguise

**Comment by ThatArcanist** [comment]
@m0kka What error is being caused by removeEventHandler and CBA_fnc_removeEventHandler?

**Comment by m0kka** [comment]
The getVariable getters in lines 151, 154 default to "" if the variable was not set/deleted, which is not a valid value for either removeEventHandler or the CBA equivalent. default variable should be -1 (or the statement executions should be guarded with if branches against execution)

**Comment by m0kka** [comment]
don't know the specific circumstances of when this will error out (since the event ids should be correctly saved most of the time), but I did see it pop up in an rpt before
