### ISSUE TITLE
Moktech cTab unable to modify MicroDagr zoom.

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#323]
Unable to change the zoom levels on the MicroDagr.
Expected to change how close or far the screen displayed.
Several ops, within the training server as well as ACE arsenal.
(Found by Beems

**Comment by m0kka** [comment]
@En013 was this bug report submitted before or after v1.7? so feb 7th?
because I tentatively fixed zooming in catTab on that version

**Comment by ThatArcanist** [comment]
@m0kka reported October 30th 2023

**Comment by m0kka** [comment]
in that case, closing as resolved q:
