### ISSUE TITLE
TX-130 not able to be moved by LAAT/C

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#324]
"Today during the op when the normal variant of the TX-130 was asked to be moved by LAAT/C and  it wasn't recognized by the LAAC/C as a vehicle even when it was almost siting on top of it. Unkown if any other TX-130 variants are affected the same way as the normal variant" -Xaio

**Comment by Rat1452** [comment]
Fixed
