### ISSUE TITLE
Hack does not progress to the next firewall 

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#335]
Issue reported by Saber

**Link to .rpt file**
https://discord.com/channels/1009176668998488164/1206563752326074471/1206763387355267102

**Comment by ThatArcanist** [comment]
This has yet to happen again, believed to be a funny arma moment. Keeping open a little bit to see if its reported again

**Comment by ThatArcanist** [comment]
Ample time has passed, closing this as cannot reproduce
