### ISSUE TITLE
Shoutgun B2 does not spawn with ammo

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#336]
Issue reported by BSJ

**Comment by Hirisu** [comment]
@ThatArcanist 
![image](https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/assets/110851104/52d63dc0-a126-41f2-bf6e-7370a6f14e96)
it got turned into a flame B2

**Comment by Hirisu** [comment]
Should be fixed with B2Fix
