### ISSUE TITLE
Changes to FS Vehicles

### ISSUE THREAD

**Issue by Rat1452** [Special-Operations-Brigade/SOB-Issue-Tracker#340]
- TX-130 Standard
- [x] Change Rounds from HEAT to AP and HE split rounds
- [x] Buff daggers 
- [x] Add horn

-TX-130 Super
- [x] ~~Change COAX rounds to proper COAX~~
- [x] Add Passenger Seats onto sides
- [x] Add smokes onto gunner seat
- [x] add horn

-TX-130 Recon
- [x] ~~Add Coax~~
- [x] add horn

-TX-130 Brawler
- [x] Add passenger seats onto the sides
- [x] Remove of coax from main gun
- [x] Addition to damage fall off or round drop at 500 or more meters
- [x] add horn
- [x] Remove HE rounds
- [x] Nerf AP Rounds
- [x] Increase Speed

-RTT
- [x] Remove?

**Comment by Rat1452** [comment]
@m0kka Would you be down to remove the RTT seeing the MUTT does everything it does now

**Comment by Hirisu** [comment]
wasnt the whole point behind the brawler, the coax

**Comment by Rat1452** [comment]
Yes, but the coax I had wasn't "coax" like it would be on a tank, so I removed the wrong kind

**Comment by Hirisu** [comment]
ah k, but i thought i put MG Coax on the brawler. 
Anyways, coax change on the super done by akeno

**Comment by Rat1452** [comment]
This is completed
