### ISSUE TITLE
Trigger doesn't activate

### ISSUE THREAD

**Issue by ThatArcanist** [Special-Operations-Brigade/SOB-Issue-Tracker#341]
When flying the Y-Wing, attempting to activate trigger yields no results

**Comment by Rat1452** [comment]
This is probably because of the armory rework and classnames, will take a look

**Comment by Rat1452** [comment]
To be specific, this line needs to be update with the proper classname
        _trigger = group _player createUnit ["mti_armoury_pilot_unit_P2_Trigger", [0, 0, 0], [], 0, "FORM"];

**Comment by ThatArcanist** [comment]
@Rat1452 What is the proper classname?

**Comment by Rat1452** [comment]
ill look when I'm home

**Comment by Amateur-God** [comment]
> @Rat1452 What is the proper classname?
 
i think its just mti_armoury_pilot_unit_Trigger, looking at the macro for it

**Comment by Amateur-God** [comment]
i had some free time so updated the class name and tested that it was working
