### ISSUE TITLE
Explosives - Config property for orienting explosive

### ISSUE THREAD

**Issue by DartRuffian** [Special-Operations-Brigade/SOB-Issue-Tracker#353]
**Is your feature request related to a problem? Please describe.**
No, it is a small implementation tweak.

**Describe the solution you'd like**
Add a config property for `GVAR(isBreachingCharge)`, which if set to 1 will run `fnc_setPosition`. Currently the function runs for all placed explosives anyway but exits if the ammo class is not a child of `MTI_BreachingCharge_Ammo`. Adding a config property also allows mods to add functionality with creating a direct dependency or creating a compatibility patch and updating the inheritance of their own assets.

**Describe alternatives you've considered**
There are alternatives such as using a setting / global value with a list of class names, but that's not necessary for this.

**Additional context**
N/A

**Comment by m0kka** [comment]
sensible, it will be done

**Comment by ThatArcanist** [comment]
@m0kka This completed yaes?
