### ISSUE TITLE
Create DC-15LE

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#65]
- Remove LE Muzzle attachment from DC-15A.
- Remove DMS Scopes from DC-15A.
- Create DC-15LE Weapon from DC-15A and preload LE Muzzle on the weapon perminantly.
- Increase accuracy and power (less power than Valken) of the weapon
- Give DC-15LE only DMS scope options

**Comment by m0kka** [comment]
added tp Core
