### ISSUE TITLE
Scuffed Textures for Specialist Macrobinoculars

### ISSUE THREAD

**Issue by Hex9909** [Special-Operations-Brigade/SOB-Issue-Tracker#82]
**Describe the bug**
The textures on the Specialist Macrobinoculars are messed up. seems they havent "seated" properly

**To Reproduce**
1. Go to 'ACE arsenal'
2. Click on 'Specialist Macro binoculars'
3. Scroll down to 'Any of the selections'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/110195350/183293587-27859abc-4917-4ed3-be20-eb36192df7c7.png)
.

**Mods List:**
 - Arca Company Modset: Y/N

**Additional context**

**Comment by m0kka** [comment]
fixed in armoury, thanks for the report!
