### ISSUE TITLE
Clone Knife ammo glitch

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#84]
**Describe the bug**
When you pull out the Clone Knife with a secondary weapon, you lose your Power Cell/Ammo and Stun/Ion Cell

**To Reproduce**
1. ACE Self Interact
2. Equipment
3. Pull Clone Knife
4. Put away
5. Check secondary ammo

**Expected behavior**
Keep your pistol ammo when swapping between the knife

**Screenshots**
N/A

**Mods List:**
 - Arca Company Modset: Y

**Additional context**
N/A

**Comment by m0kka** [comment]
tried a different way of putting the ammo back in the guns, will see if that fixes it

**Comment by m0kka** [comment]
haven't heard anything about this since, closing as resolved
