### ISSUE TITLE
Assassin blades

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#86]
**Is your feature request related to a problem? Please describe.**
Since the introduction of the Clone knife, the Assassin blades seem a bit useless. Especially when considering that even the vibro blade of us commandos does more damage

**Describe the solution you'd like**
Increase the blade damage to insta kill atleast a B1

**Describe alternatives you've considered**
Having it so that the blades instantly go into the combat kill animation

**Additional context**
-none-

**Comment by m0kka** [comment]
closing this as not feasible, not intending to mess with IMS code any more than I have to (and *definitely* not adding a dependency to IMS just to edit the blade damage)

may revisit if we ever make our own blade models
