### ISSUE TITLE
Detection radius of Epsilon

### ISSUE THREAD

**Issue by Hirisu** [Special-Operations-Brigade/SOB-Issue-Tracker#88]
**Is your feature request related to a problem? Please describe.**
The Detection of assassins still seems bad

**Describe the solution you'd like**
Reduce Detection radius / make Epsilon harder to spot by AI

**Describe alternatives you've considered**
-none-

**Additional context**
the AI is still very aware of assassins even if there are objects or other things inbetween them, this makes it hard for them to stay hidden.

**Comment by m0kka** [comment]
implemented in Armoury
