### ISSUE TITLE
Integrating UAV terminal with CTAB

### ISSUE THREAD

**Issue by oliv3lrg** [Special-Operations-Brigade/SOB-Issue-Tracker#90]
**Is your feature request related to a problem? Please describe.**
The Recon Sniper will get access to the cTab and the UAV Terminal, while he has a UAV Terminal he cant use the cTab and vice versa.

**Describe the solution you'd like**
I'd like to see an Item that you can put into your inventory which will give you the ability to open the UAV terminal without having it in the GPS slot.

**Describe alternatives you've considered**
Switching around between cTab and UAV Terminal.

REQUEST MADE ON BEHALF OF WINCHESTER

**Comment by m0kka** [comment]
this isn't relevant anymore
