### ISSUE TITLE
ARC Bracer Rocket

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#95]
**Describe the bug**
MM9 reticle stays after death
**To Reproduce**
1. Equip SOB ARC Trooper Bracer
2. Prep MM9
3. Lock onto target
4. Die
5. See reticle, cannot fire on it.

**Expected behavior**
Reticle should vanish after death

**Screenshots**
![image](https://user-images.githubusercontent.com/76742077/185942731-87da5c19-24ec-4438-882a-0ca1c5e79d35.png)
After death, cannot fire rocket (intended I would assume)

**Mods List:**
 - MokTech Industries - Core: N
 - MokTech Industries - Armoury: N
 - MokTech Industries - Factions: N
(Running current Aux)
**Additional context**
Multiple reticles can appear
Reticles vanish when vehicles are deleted
![image](https://user-images.githubusercontent.com/76742077/185943352-179b9522-b7b4-454c-b82d-ccd534e2e7fa.png)

**Comment by m0kka** [comment]
fixed in Core, thanks for the report!
