### ISSUE TITLE
Clone Pilot Survival Pack Variants

### ISSUE THREAD

**Issue by gumbekk** [Special-Operations-Brigade/SOB-Issue-Tracker#96]
**Is your feature request related to a problem? Please describe.**
Survival pack looks bad on ranked pilot armor

**Describe the solution you'd like**
Rank based survival packs to match the armor more/just more variants

**Describe alternatives you've considered**
N/A

**Additional context**
Were supposed to be added in the accessories update as promised by Celt, moving it up to github for organization and reminder
https://discord.com/channels/898948967935639562/925810352812355584/998316392426242050 (discord message link)

**Comment by m0kka** [comment]
sorta done
